### PR TITLE
Add: READMEにER図を追記

### PR DESCRIPTION
**Pull request by tarakish**
READMEにER図を追加しました。
[https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram…](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio#R7Z1Zl5s4Fsc%2Fjc%2FpfnCOQWx%2BLFcqPT2dzEwnvaTzUkdlVDZdGNyAy3Y%2B%2FQizGslVgIWgkJKeCWYRIP0vPy1XVxNwuzn8FMDt%2BpNvI3eizuzDBLyfqKpizef4n3jPMdljzEGyYxU4dnpSseOL8x2lO2fp3p1jo%2FDsxMj33cjZnu9c%2Bp6HltHZPhgE%2Fv78tEffPb%2FrFq4QsePLErrk3j8dO1oney3VLPb%2FCzmrdXZnxUhfeAOzk9M3CdfQ9velXeBuAm4D34%2BSrc3hFrlx5mX58ufPxz%2Fdj0%2FGT%2F%2F%2BNfwH%2Fr745bf%2F%2FDFNEvvQ5JL8FQLkRa2Tdm4eNubm407968uj9eGgo9%2BtYKolST9Dd5fm1y5EQZi%2BcHTMchG%2F%2BzbejOBDvGsRRjCI0sIGM7wDF18EHQ8FeIdy%2Bu26cBs6p9Pfn85YO679ER79XZQllP1aPDoHZH9Oyjq%2BGhf7R5xYmF76iBP%2Fkj5MfBi6zsrD20ucH%2FEdF1vfibfunvGOLI1Hx3VvfdcPTm8AbB1ZtnZ69MB%2FQqUjlvoADAMfqZnNaXE8oyBCh5LI0mz%2FCfkbFAVHfEp6dGoaqYRSG9LSn%2FtCkCBT2bokRpBdB1MjWOVpFwWNN9KyblDuOlHuF4sc50fkQPczNk7orU6lv442bprL%2B7UToS9buIxP3eNPCLXs7cDf%2FgaDFYrSHa8VmOd78Y0if5te4KLH7NoHP4r8TaaUNLfyRE85pS%2Fwfzjvbmfv9ImO3%2BYW%2F1aK3%2Fi%2F%2BPQguvU9rAcs3DgNBMNoj8KIKoUXzed1KaQlD%2BqWfFcFbxAF%2F79fmBb96SsOi6JvXKqzSqn6OHcf3dOHd%2B3YNvIuyKdmkem1i6xURqbarIjSxIqMa5wadPH7eTBCC3%2Fn2SFR7vlztpeCSUgBnz5oKWTf%2FeTcRYhv6Hirj8mVRp9aOZyXbKmwVc1iqZ1ayXEQjzUGgFT19QYAYvQNkHm3BT90fFi1C2zs%2BMgaeCUleHCDhq0G3gSpLxfhCKIohH4kQnggZN43QhRVbIYo9XsQRg8RQEgBPsMIBsMWBG%2BMNFCMcBxRdYkNHthQ1L65oRrD%2FiowNnpVdlXlWUH2VaENdNxh64E3JRoIRjxKWJISXCih906J%2BbC%2FCqyNXvZIZVkByB6piWq46bfXO9OE8c8uHrdfPMDl0yqIH2m6TEr1Bp8XrB5%2BUHX8OY1NDP9%2FZfvH4nq8tYr%2FXQbHbYTs%2By2EYbj3Azu7M36T5ObJecPWJndiyf6xy2pWJLG4EMvqm1hArO4vILu%2F8qwgu79CfNthy4E3JBroRTxIaBISPCCRu7P2Bwm23ZyDh0T9Iho9JEifvQCFKMJtjaSpcR%2F5Tzi%2FBy0P7tCorx%2FhoKEBCQ0u0Kjt590VNDS21YOhQyMTtoTGVKN5%2BJf7wpLuKBpI7tFh6wTIvodRdslDUPRfyW4tljoUDz4zplqR8LkEH7N3%2BLDtwBw8fGa1i2j08FFfgQ9lIKYy%2BjLLx1tKWz%2FGm3GBzOIZgdNHuHHcY3INTghutqeDANf9sZ6Q%2B4wiZwmJI%2BeJhKdJjHESiro9VI4lTxkf9PxgA93zw%2Fs0l%2BPjWvKcp4MuinAWT1PMUK%2FHCommKZZuTpdgvZ4ddDz7pLf46Kz0YKeD%2BEPihY84ySxxD%2BUnxCA%2Fv3f58hfGu2JAZGNc2rzY1kv5bjvh1oVpnjue65RujG0JRuUHqo6RVSobJw%2BO%2BxC%2FZammIesVbD4xwtUrgCnrFXxmsPZdrwBsXXmGXq%2FIhC3rFVNATj7b7eSk1dZ6EQ4SGlvfMAmJS5DoPc6BzrabYeiQyIQtITHVyXmFge%2BiH5C32%2Fw4bFFwb0%2FUV41wqDDJUddHFz77MjgS2%2BBIIHO%2Fy2IjUdzxche9sibynczZYZKzTd5gtaH%2F6Ei5CV0THola9p1VG0wyrolg8ZHMVs1NrWEhvcyAOqnxQADZ3JSNzdZqOZyXbdnE2aqnVnI8QiTRpqO8OYz03%2FpsjhFKkCS%2BGLE6jm0ydIjk0pcQscixUBkm6Qq9iIcRco6IxAgXjFACJXHGCBmeedjfDdafhVb%2BnOPECOnPaaNwGTjbyPGl739b2QhHEzCT9OBDD1q8JL74ADO2Ez2Gjotc25IXOC%2FIuoOzidfKGLQiuDtLNJCMcKyw2MZbk6i4iApK0CTOLQ223pNDJ4VVv4jGDgqLHPGK%2FcO30l%2FiKtkIBwuFUuHAMgifkIOkywRTl4mpkpXv5fWk6J%2BXztaTUmZyRSkmlYfCjK5xmmiMqisLX%2FhVpQr9N6pR6IAlCuqkxoUEcmUplno5nJfuWRvBZFqVqJMcFwHJ1aX6ggnFdYI3TARfYapQv0SJIheZYqwY8WAi15nqDSYUBwrOMJFLTbUKtjtSmJCeVNKHgoFwBGSKDLvLCSE0LwreDBEr8m4ubokMnBeUWaAIufjTex%2F598n4xvF%2B70Rr%2FNtb7RAZMVEOpF2nMQHpIkMZ8aILxfGCN13EimaUi1vSBecF2dWZxBi4x3aAvFW0lvC4TkLiwSOrL0t4dA4PSqQKzvBQxQqxm4tbwgPnBdm1GeAMdJ3oOGxRcOdFA9UIyAu5GAgnXtDWkOLNC7HWA8nFLXmB84L00NwGzlKOpbeWjICwkDOCeMGitk93d7AQa05QLm4JC5wXpAem63hP8aAH3MDvcrS8vXbGTI31LTp8%2B%2F5J%2Ffb3r4vV%2Bz%2FQ7f7rz1NVMoNkBiGU%2Bhi5zAzKkk%2BdMYNa1KSDzYdRzQN5pdQuy3%2FUCKG%2BNjkb0A5iguzh8V6w2SAMVSMcPNj63kh4XIQHbV0fvvAgXW0kPHQx4UFOILSdMMLFhQJJj%2FayEY4ebH1rJD0u04PnJHRqUZOuNJIelpj0oEwaDD24fJLkaC2ZMZOD%2FsEDKlkHyRqwMp5NWjCM4tnk9Gi8BpDOACcXyn8UYbcHENAmN6S3swqQAsjeK9EC2oBWrhOjDJGnANJ1QrCqBFO9iBcbD5B9W28QJgNwpGgOk97XAlJAx8sJDh8lMtpqkRekY4UMaHONYgSESccBsiRMLsKk9xWBchGKC5NWK52PEyYaGdpKBrRhIBzhmKLKkAO8ENL%2FskCqYCEH1HYhB0aJDJUSckAuC3SVZISDhWJQqh2Ze45c7IH5Yg8ZMBoPjlmdtUIMlVDAG6w%2FDGBwzKivh8EMjhnkyKhog2O5%2FmWNQjEoCw3aw5YD97ZnA70IWJ0YxdJBA2iMNodJ%2F4NjRscjo8NHSauFg0aKEnKkVA6OXaMYAWEilw7qCyb9D44Zoi8dZLRaOmicMMkmw8vBMbbCEY4pKuOoaRIhQx4cU8Va7SEXt0QGzguyMSoHx66SjHCwUEy2IZklLC7DgrJ4A%2BcGhylY%2B8KsX0hjh4ViksNgS3y3TFeD1QT3tkUD0YiHC4vssjjNVZdeFEy9KDIsDGiCcdZd9rZ7KgfgQ5Gb0BvyoZiTLlSi%2BVDk%2Bpd1CWWuEnKQPhTt9SJeNWI%2BimgVA2iGNodJ%2Fz4Uc9IDa9jfDuafBhmrosgL0ptK%2BlBcoxgBYSKjVfQFk%2F59KOaiR6uYy2gVRV6Q3lTSh4KBcARkylwihA9CBuBDkYWSH%2Bqngbnly5gURdmTPZvSh%2BIqyQgHC1Uju0OxDsIn5KDwfu9E6%2FtHFz77wSgGyVz4gNwFXD6tgjhHMxnb6BHu3GhCjKI96vHf9G6l%2FcmfCWV0zTj9oYqTzegaqAyv0dYSoQ%2BvqZ0xSBtFj2iHw2uv6q7mp6yw1rcz%2FqZq4w3wy65cZa9qkRcCRwDuQ1AC1nlkp%2BtgedX7EJ%2Bqkb2yY1nehl25yo7bIi%2FIjtukBSXQ8ml9CEtAbsloxIPlVu%2BjiWrmPiu5VcOCJLdUnew9Trr6JLa61JV42KIEnYrwNxsX2b3nRzKIJeMglmbWhHphAgZQKdrINcmeTV2HnnrzPcR1PzQNAhJd7gCmln53FRNKqKmxdADXLrZW7eVsyisbHtRJjQsOyPayMBWODvRyOC%2Fds0WhLZb6qZUcFwHJZnBfMKH0znKGCSXU1LC%2FHcw%2FDa2asONEiUk2YZf%2BZhPn4KA1wZ8njdunAvEke1XJE%2B48ofSa8uYJ6bs0ll7TusWW618SRTVJZ6VdiATqEu1ANAIShW1gQwmQRjMweBOE7NsUjiCtAuuPlCBkb6dw7iAd6EZAiLBdOlJC5DJEKNEteUOE7NMUDiKtAuqPEyIW2cspmm9GB7IRjyGWjJDMiyF1vSy6Y4hF9mOKxhCrvrvM%2BBlC9mzageM93e%2BhbIpcoxzxMCIjivDCiKr0jZF8QrnAGGkXZGSUGAGUICOnqOkSIVeoRjiEgBnpBP7g%2B08bGIwj%2Fv4IQotMq7FFaHMU%2BIYWATPpOM5nylthoG8ntAiYjdeznF25yqnaRV4I7Hreh6CEm%2BsGZtI3fbC86j20CFDG27RmV65yinahF7LtLZY3Yh%2BqEg9aCjlwJKE1EGj1HlcEKOP1kGdWrrkFSWgBhXShF84Bsg9hCcgtsk95ohpJb6sfzwGcLfPuU%2BOfnZ9kPNAUiP9X3mWsTv%2FeqZO5MblRJncfJovbyfxmcgcmFpjM704b6mQxzzY%2BpIfwacmGZVT3zLM9N4vsqfBrJg%2BW3jDd%2FRBU97z0%2BCaM%2F9Z7fG2ysCY37yd38%2FjQHFz1sBXLPSkb2S9YaMmAWxgEo3jZ1WgoFPMwKXpWlO6AWqNPG9krlI1B4IrJ2l%2F5HnTvir3JKEUyJII%2FEmeZjTz7JghOX6m7z%2Fg7%2BJv%2FCXrHSTqOUhzaQM%2F%2B7%2BkzWZRlNgBSGngwb%2BK%2Fp3Tx%2B39NTzr9%2BCv%2B8U7Pfr4%2FlA%2B%2BP2a%2FDk70tbRdugr%2FKi6Kf2TXNNND6O%2BCJXoh09MvRZTVOi%2Bdlw%2FJxQVQl%2BPKjCagbGeAXBg5z%2BXUXvzq%2Fi%2FmSWlUxlCqCq4oM3n59LJCnGRKeiUlUE0pyR4iJawYeCydltasLz%2ByNTu%2FkaW%2F%2FGDV8%2FXzC%2FBG8giM8VFj%2Ba1h26HSzA6b2VQNW9EHZitKReDztpYC5ucJGdURTkaWogDqA196rurpmv7y%2BcR7NL7AUHhYYpa7wljiAIioAFDXzjPfyMHY%2BVTXzmVq6m0tXaukZFRTYsVEYFYYp74CxeoFhsnDFIFopsgaipkX2GCMRa20gPRqU72%2BrVTwY6TVNNa2cumJLz2Yal13vjnjYlnkYM64LSuDnNIf5LLJ2DXqstbAzBa3T%2Bbv5qU%2FVkXjFdtrYsXvZqU%2FasWmNdpdGVu4Pm8Gw%2Br5WYzbyy85u%2FICQ2P7TVjfosO375%2FUb3%2F%2Fuli9%2FwPd7r%2F%2BPG3IWmwTTnT8fNKV73H6KrTt9KGaUw89OunQb5%2BGXMFZjp%2FGplsFo1JN6YJ5stJrQ4L1q1duTbLuNK7Maqs8GSiSKmeh8qFX1NpUrK5rHjGRODWz1ZoCT7sr%2BhN4pe0DWsu70uGgmfXU3bhrsXIf8EoVq3q%2BprxSY7r6gkqlr5sqVh3fJmnMjIy5Lq0Uo2da5TOWMuNo3ZpSwHkrLWtxXmqmsbJuvfIC%2BivWXTlfU182VvOq0%2FlYdo1Vp9%2BcZXdtoVa%2FdkcyoO1gtmooFcl1g9FqXyF4ZSyb6It8xXIuvUe3pkO66A3MdPrpdHi9mzBZn%2FLtj3AT%2FDA6Mh%2BN%2BrwXraFaaWU85kW3Bpob4RisYYhdGvlSea%2FaWlKT6s%2FUqnWaqkNgbVOr1qWqCTEyNVCt4s1eJlX1%2FCsrbfhn4McOqcXpAdyuP%2Fk2is%2F4Pw%3D%3D)

下記、わかりにくい用語、意味について補足です。
  - `distilleries`…distillery（蒸溜所）の複数形
  - `flavors`テーブルの`group`…フレーバーを６種類程度にカテゴライズする用途のカラム
  - `whiskeies`テーブルの`feeling_to_whiskey_with_tongue`…飲み口（軽い、濃厚）を5段階程度で管理するカラム
  - `whiskeies`テーブルの`flavor_strength`…香りの強さ（軽い、濃厚）を5段階程度で管理するカラム
 
以上、お忙しいところお手数ですがご確認、レビューのほど、よろしくお願いいたします！！

### CODE REVIEW

**Comment by tarakish** [comment]
誤字と脱字を見つけたため 1d99fe2 , 9c5ceb6 , 86f0fec にて修正しました。
PRに記載のリンクは修正後のものです！

**Comment by tarakish** [comment]
レビューでご指摘いただいた点を元にER図を 28800a4 にて修正しました。
重ねてお手数をお掛けしますが、ご確認と再レビューのほどよろしくお願いいたします！
下記、補足です。
- 関連付けの定義が誤っていた点を修正
- 語句の修正
  - `whiskey`の複数形が正しくは`whiskeies`ではなく`whiskeys`だったため修正
  - 希少性を表す`rarity`が`rarelity`になっていたため修正
- カラムの追加
  - ウイスキー詳細画面でウイスキー毎におすすめの飲み方の詳細説明を、ウイスキーそのものの説明と別枠で動的出力したいため、`whiskeys`テーブルに`detail_for_drink_way`カラムを追加
- カラムの意味の補足
  - `whiskeies`テーブルの`feeling_to_whiskey_with_tongue`…飲み口（軽い、濃厚）を5段階程度で管理するカラム
  - `whiskeies`テーブルの`flavor_strength`…香りの強さ（軽い、濃厚）を5段階程度で管理するカラム
  - こちらのカラムについてenum型にした理由ですが、例えば`flavor_strength`の場合、満足度アンケートのように（1 … 軽い、2…少し軽い、3…バランスが良い、4…少し濃い、5…濃厚）と数値と言葉をセットにして管理したいと考えたためです！

**Comment by murata0705** [comment]
問題ないと思います！マージして大丈夫です！

このあたりの関連も中間テーブルにする方法もあるかなとも思ったので、一応書いておきます。
（ウイスキー素人です。）

- tasting_notes - flavors
- tasting_notes - drink_ways
- tasting_notes - snacks
- whiskeys - snacks
- whiskeys - drink_ways

**Comment by tarakish** [comment]
レビューいただきありがとうございます！

コメントいただいた
- whiskeys - snacks
- whiskeys - drink_ways
こちらを多対多にするかどうかについてですが
現時点で実装予定の機能としては、一つのウイスキーについて
- おすすめの飲み方
- おすすめのおつまみ
を一つのみ持たせる

**Comment by murata0705** [comment]
うーん、ちょっとどうなんだろう。なんかやっぱり snacks has_many whiskeys がしっくりこないですねぇ。。

- whiskeys - whiskey_snack_pairings - snacks

とかにして、コードで 1対1 にしておくとか。

でも実装上は問題ないから大丈夫かな。
すみません、ちょっと気になったのですが、別に問題があるわけではないのでそのまま進めてもらって大丈夫です！

**Comment by tarakish** [comment]
レビューいただきありがとうございます！

コメントいただいた
- whiskeys - snacks
- whiskeys - drink_ways
こちらを多対多にするかどうかについてですが
現時点では、一つのウイスキーについて
- おすすめの飲み方
- おすすめのおつまみ
を一つのみ持たせる、というような機能を考えております！

追記いただいた点に関して自分もハッキリと言語化出来ず申し訳ないのですが
> snacks has_many whiskeys がしっくりこない

こちらはデータ上は問題ないものの、実際の概念として考えた時に
「一つのおつまみが多数のウイスキーと紐づく」ということが実態に即していない、というような意味でしょうか…？

**Comment by murata0705** [comment]
> こちらはデータ上は問題ないものの
「一つのおつまみに対してウイスキーが多数紐づく」ということが概念的に実態に即していない、というような意味でしょうか…？

はい、おっしゃるとおりです。

- whiskeys
- snacks
- drink_ways

は、独立している概念に感じるので、独立させていおいたほうが拡張性が高いかなとは思いました。distilleries は、各銘柄は決まった distilleries でしか作られないというのなら、今の形でもしっくり来る感じですね。

> こちらを多対多にするかどうかについてですが
現時点では、一つのウイスキーについて
おすすめの飲み方
おすすめのおつまみ
を一つのみ持たせる、というような機能を考えております！

すでに考慮された上で現状の上記の仕様でいくということなので、実装は問題ないと思いますが、今後もメンテや新機能の追加を考えているのであれば、独立させたほうが拡張しやすいとは思いますね。例えばすでに考慮されているとは思いますが、複数の飲み方やおつまの組み合わせを表示したり、おすすめの組み合わせをランキング化したりする場合ですかね。

ただ、スケジュール面や今後の計画もあると思うので、今のままでも良いと思います！

**Comment by tarakish** [comment]
詳細かつ丁寧なレビューありがとうございます！
> 独立している概念に感じるので、独立させていおいたほうが拡張性が高いかなとは思いました。

なるほどです！
確かに仰られている通り、拡張性を考えると独立させた方がいいと感じました。

ただ今回に関しては今のままで進めようと思います！理由は主に以下2点です。
- 機能をリッチにする、というよりはむしろ機能を絞って分かりやすくしたいという方向性のため
- そもそも論ですが、正直このアイデアに対して自分としてはあまり自信がなく、作成後少なくともあと一つは違うアプリを作成予定のため（このアプリの反響次第ではありますが）新機能の追加などはあまり考えていない

せっかくご提案いただいたところ申し訳ございませんが、「独立した概念は多対多にすることで独立させた方が拡張性が高い」ことは大変勉強になりました！

**Pull request merged**
